#!/usr/bin/env bash
# Compile the Java project.
javac -encoding utf8 -cp src -d bin/ $(find src -name '*.java' ! -name '*Test.java' ! -path '*/test*') \
&& echo "Compilation successful." || echo "Compilation failed."
